name: Program Code Convention

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  python_lint:
    name: Python Code Lint
    runs-on: ubuntu-latest

    steps:
      # 1. Клонування репозиторію
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Встановлення Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Встановлення pylint
      - name: Install pylint
        run: |
          pip install pylint

      # 4. Перевірка файлу ProgramCode.py
      - name: Lint program_code.py
        run: |
         echo "=== Checking program_code.py ==="
         pylint program_code.py --exit-zero


